application: mumble-ios
version: 1
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: static
  secure: optional

- url: /_tasks/.*
  script: runner.py
  secure: optional
  login: admin

- url: /remote_api
  script: remoteapi.py

- url: /.*
  script: runner.py
  secure: optional
