#!/usr/bin/python

from __future__ import with_statement
import dataurlify

images = {
	'background':    'static/bg.png',
	'topbar':        'static/topbar.png'
}

with open('images.py', 'w') as generated:
	generated.write("# this file was automatically generated by scripts/genimages.py, don't touch!\n")
	for name, path in images.items():
		generated.write("%s = \"%s\"\n" % (name, dataurlify.generate(path)))
